# Generated by Django 5.1.2 on 2024-10-11 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batter",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pitcher",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="BattedBall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("game_date", models.DateField()),
                ("launch_angle", models.FloatField()),
                ("exit_speed", models.FloatField()),
                ("exit_direction", models.FloatField()),
                ("hit_distance", models.FloatField()),
                ("hang_time", models.FloatField()),
                ("hit_spin_rate", models.FloatField()),
                ("play_outcome", models.CharField(max_length=100)),
                ("video_link", models.URLField()),
                (
                    "batter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="braves.batter"
                    ),
                ),
                (
                    "pitcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="braves.pitcher"
                    ),
                ),
            ],
        ),
    ]
